### ISSUE TITLE
Ошибка в тексте

### ISSUE THREAD

**Issue by iAmFoxik** [belvasevg/KUKA_course#1]
> # Что находится в отдельных директориях с примерами
> Директории содержат в себе примеры с .src и .dat файлом. Также каждая отдельная директория содержит в себе отдель readme файл с описанием и либо демонстраций полного цикла работы, либо результатом работы отдельных модулей.

В тексте есть ошибка))) "отдель**но** readme"

**Comment by belvasevg** [comment]
Спасибо!
